openapi: 3.0.1
info:
  title: ytlargeGPT
  version: '1.0.0'
paths:
  /analyze:
    post:
      summary: Analyze a YouTube video
      description: >-
        Accepts a YouTube video URL and returns metadata and a simulated
        monetization flag.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: Full YouTube video URL
                  example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      responses:
        '200':
          description: Video analysis results
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  channelId:
                    type: string
                  channelTitle:
                    type: string
                  views:
                    type: integer
                  uploadDate:
                    type: string
                    format: date
                  category:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
                  monetized:
                    type: boolean
servers:
  - url: http://localhost:8000
    description: Local development server
