openapi: 3.1.0
info:
  title: YouTube Monetization API
  version: 1.0.0
  description: Returns monetization eligibility and stats for videos/channels.
servers:
  - url: https://<your-leapcell-domain>.leapcell.dev
paths:
  /youtube-monetization:
    post:
      summary: Get YouTube stats & monetization
      operationId: youtubeMonetization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              oneOf:
                - required: [video_url]
                - required: [channel_id]
              properties:
                video_url:
                  type: string
                  format: uri
                  example: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                channel_id:
                  type: string
                  example: "UCBR8-60-B28hp2BmDPdntcQ"
                prompt:
                  type: string
                  example: "Is this monetized?"
            examples:
              video:
                value:
                  video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                  prompt: "views"
              channel:
                value:
                  channel_id: "UCBR8-60-B28hp2BmDPdntcQ"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              examples:
                video:
                  value:
                    title: "Rick Astley - Never Gonna Give You Up (Official Video) (4K Remaster)"
                    views: 1680713497
                    likes: 18000000
                    comments: 2400000
                    published_at: "2009-10-25T06:54:00Z"
                    duration: "PT3M33S"
                    channel_id: "UCuAXFkgsw1L7xaCfnd5JJOw"
                channel:
                  value:
                    title: "Rick Astley"
                    subscribers: 4380000
                    video_count: 200
                    total_views: 2500000000
                    estimated_watch_hours: 125000000
                    monetization_status: "eligible"
        "400":
          description: Bad request
        "404":
          description: Video or channel not found
        "500":
          description: Server error
